### ISSUE TITLE
Problem with the relationships between nodes.

### ISSUE THREAD

**Issue by pezzo98** [micwan88/d3js-neo4j-example#6]
Why don't queries automatically link nodes that have a relationship?
For example this query " MATCH (n:Processo) RETURN n " in neo4j browser returns all nodes with relationships among them, while the same query into "ctm-query.html" returns only nodes.

**Comment by pezzo98** [comment]
One way to solve this problem is to return the relationship within the query, for example:
MATCH (froot:Example) where froot.name='Test'
MATCH path = (froot)-[]->(f:Example)
RETURN path;

Meanwhile it is the only one I found.

**Comment by micwan88** [comment]
Oh, yes, I got the same problem with you and I didn't know why neo4j browser can return all relationships but I can get the same in js query.

Thanks for your suggestion and let me try it

**Comment by zhang99969** [comment]
Any new solutions found?
